### PR TITLE
Prep for 0.8.9 release.

### PR DESCRIPTION
**Pull request by lakshmivyas**
- Update changelog
- Relax dependency version requirements
- Update readme
- Read setup.py requirements from requirements text files

### CODE REVIEW

**Comment by lakshmivyas** [comment]
@jonafato , @llonchj - Ready for release?

@jd, @moorepants: Are the requirements relaxed enough for your use cases?

**Comment by jonafato** [comment]
@lakshmivyas For the record, I'm still of the opinion that the requirements should be pinned. Relaxing requirements like this may solve some short term issues, but it's not going to solve the core issue of conflicting dependencies given how Python packages and pip work. The sustainable way to use applications like this is via virtual environments.

That said, I'll defer to your judgement here, and the conservative upper limit on requirement versions is a safe approach to preventing breakage when dependencies update (as long as they follow semantic versioning).

**Comment by lakshmivyas** [comment]
@jonafato - I am in agreement (hence the aggressive version fixing before).  Also, in the past, I have also used a requirements file for the website to override any of hyde's requirements when needed.  As far as #290 is concerned, I can also see where @jd is coming from (w.r.to  linux packages and non-technical users).  

My thoughts:

Ideally, the dependencies that I have should only cause an issue if one of the packages has breaking changes.  In those cases, we can come back and tighten the requirements.   This ensures that hyde is not stuck to old versions and makes the life of package maintainers easier.   Over the course of hyde's existence, there were only two such breaking changes, so I think having a bit of an open requirements is good for now.

At some point when hyde gets frequent enough updates where we can manage newer versions as part of other fixes, development, we can tighten the requirements.   Right now, this approach reduces the maintenance burden on hyde, enables package maintainers and users to get updated version of the dependencies at the risk of causing occassional breakage when one of the dependencies misbehave (which can be easily fixed on both ends).  

What do you think?  \cc @llonchj

**Comment by jd** [comment]
I'm not a fan of the upper limit, but at least this is way better than how it is now, so thank you!

And I agree with your thoughts @lakshmivyas. There should not be any reason to put artificial boundaries like upper limits. If it breaks, just come back and either fix the compatibility or add an upper bound.

**Comment by moorepants** [comment]
I'm +1 for this. I think it is very reasonable to expect non-breaking changes among minor versions.

**Comment by llonchj** [comment]
+1

2015-11-06 23:44 GMT+11:00 Jason K. Moore <notifications@github.com>:

**Comment by lakshmivyas** [comment]
@jonafato - I will go ahead and merge this and push to pypi.  Lets revisit this if we hit a snag.

**Pull request merged**
