### PR TITLE
[WIP] Add Sphinx docs

### PR DESCRIPTION
**Pull request by jonafato**
This is the starting point of documenting Hyde using Sphinx. This
provides several benefits:

1. Code and documentation live together, so it's easier to track and
enforce that there exists documentation for new or changing code.

2. This lets us get Hyde on Read The Docs.

3. We can use things like `autoclass` where appropriate to pull
documentation directly from source code without reinventing the wheel.

I've tried to replicate what currently exists on hyde.github.io. The
first pass of this effort is concerned with parity, and we can continue
to improve from there on. Steps:

1. Convert all existing documentation on hyde.github.io to Sphinx. This
is covered by this commit and should be considered "in review".

2. Open issues for core parts of Hyde that are missing documentation.

3. Close these issues individually. This is a great opportunity for
community members wishing to get involved to contribute.

4. Require significant changes in code to be accompanied by updated /
new documentation the same way we would require tests.

While these steps are in progress, the following should also be done:

1. Deprecate the docs at hyde.github.io, linking users to Read The Docs.

2. Replace the content currently hosted at hyde.github.io with a new
brochure site showing off some of Hyde's uses and linking to other
interesting content (e.g. a list of themes, links to sites powered by
Hyde, etc.).

References #188, #209, and quite a few other issues.

@lakshmivyas, @llonchj: please review. This is a starting point for
Sphinx docs, and the PR is labelled as a work in progress, but I have no
specific threshold for it being "done". Once we're all satisfied with
the first pass, I'll set up RTD, and we can start filing issues for
specific areas lacking docs.

### CODE REVIEW

**Comment by jonafato** [comment]
Something seems to have changed between ``pygments==2.1.0`` and
``pygments==2.1.1`` causing an extra ``<span></span>`` to be generated
by the Jinja2 and Markdown code block tests. This PR updates the
tests to reflect that change, but a more permanent solution should be
developed if possible.

**Comment by lakshmivyas** [comment]
This is looking great @jonafato.  :100: 

Minor changes in markdown and other libraries breaking hyde tests have been a recurring issue.  On the one hand these tests make sure that our rendering works non-intrusively on the other hand we are essentially testing other libraries.    If we could wrap our tests so that we compare hyde generated output with output generated by the libraries instead of hardcoding the output, we may get rid of some of the pain.

**Comment by lakshmivyas** [comment]
I think we can make a release once we have RTD setup (even with sparse content) and make an announcement about the docs and opportunities for contribution.

**Comment by jonafato** [comment]
@lakshmivyas Agreed on wrapping our test data to make the output testing more robust against minor library changes. I'll open a separate issue for that.

I think doing a release (or at the very least, a pre-release) is a great idea (especially to get the Python 3 support out there). If you think this is sufficient for a starting point of documentation, I think it's ready to merge. Once it's merged and the docs are up, I'll work on some issue gardening and try to identify good candidates for contributor documentation.

**Pull request merged**
