### PR TITLE
Dedupe deps

### PR DESCRIPTION
**Pull request by moggers87**
This pull request changes the way we use `requirements.txt` to avoid having two identical lists of dependencies.

### CODE REVIEW

**Comment by llonchj** [comment]
@moggers87 Thank you for the PR, we will review and merge it soon

**Comment by llonchj** [comment]
@moggers87, Great contribution! Kindly rebase and MR again.

**Comment by moggers87** [comment]
Rebased on current master

**Comment by llonchj** [comment]
@moggers87 Thank you!

**Pull request merged**
