### PR TITLE
Add initial (experimental) Python 3 support.

### PR DESCRIPTION
**Pull request by jonafato**
All tests* currently pass under Python 2.7 and Python 3.3 - 3.5. This
does not mean that Python 3 support is stable, however. As a plan
forward, we should encourage interested users to run Hyde with Python 3,
report bugs, and submit patches. This change references the Python 3
Support issue on GitHub (#270). Once this becomes a bit more tested and
stable, that issue should be closed, and Hyde should announce official,
stable support for Python 3 (i.e. new changes must also support 3,
issues with running hyde under 3 should be considered bugs rather than
feature requests, etc.).

Changes:

- Add ``hyde/_compat.py`` for 2-to-3 compatibility helpers.
- Replace uses of 2-specific code with their ``hyde._compat`` versions.
- Tests remain largely unchanged (for good reason). The exceptions here
  are to ``print`` function calls, and ``str`` type usage, and
  compatibility imports.
- Replace explicit calls to ``foo.next()`` with ``next(foo)``. This
  keeps code portable between Python 2's ``next`` and Python 3's
  ``__next__`` methods without the need for any compatibility functions
  and is the recommended API for interacting with these methods.
- Replace deprecated (and, in Python 3, removed) ``except Exception, e:``
  statements with their updated ``except Exception as e:`` versions.
- Replace print statements with print function calls (because of how
  parentheses work in Python, this is transparently
  cross-version-compatible).
- Add Python 3.3, 3.4, and 3.5 to ``tox.ini``, ``.travis.yml``, and
  classifiers in ``setup.py``.
- Add ``{posargs}`` to ``tox.ini`` command invocations to improve usage
  during development.
- Add Python 3 note in changelog.

\* asciidoc does not support Python 3, and fixing that far beyond the
scope of this task, so the test that deals with it is conditionally
skipped when run using versions of Python 3.

### CODE REVIEW

**Comment by jonafato** [comment]
Note: this PR still has a few minor changes being made. I'll post another comment when it's ready for review / merge.

**Comment by jonafato** [comment]
@lakshmivyas @llonchj Please review. I tried to centralize the compatibility checks as much as possible in ``hyde/_compat.py`` and not include any unrelated changes. This PR touches quite a few files, but the changeset is still a reasonable size.

One change that may need some clarification: the version of Python used by travis is being changed from 2.7 to 3.5. This is required because travis does not currently make Python 3.5 available on older runtime environments. Everything still happens through ``tox``, so the correct versions of Python are still used while testing.

**Comment by lakshmivyas** [comment]
@jonafato : Fantastic work :+1: .   I will review in detail this week.  Consolidating the differences in _compat.py is awesome.   Very nice.

**Comment by jonafato** [comment]
@lakshmivyas Any updates here?

**Comment by lakshmivyas** [comment]
@jonafato - sorry, busy month at work.   So, I found one issue - `with_exception` needs compat support.  

```diff
diff --git a/hyde/_compat.py b/hyde/_compat.py
index f3fc8fc..0dc9e77 100644
--- a/hyde/_compat.py
+++ b/hyde/_compat.py
@@ -81,3 +81,13 @@ def with_metaclass(meta, *bases):
                 return type.__new__(cls, name, (), d)
             return meta(name, bases, d)
     return metaclass('DummyMetaClass', None, {})
+
+# Note: from https://github.com/Pylons/webob/blob/master/webob/compat.py
+if PY3:  # pragma: no cover
+    def reraise(exc_info):
+        etype, exc, tb = exc_info
+        if exc.__traceback__ is not tb:
+            raise exc.with_traceback(tb)
+        raise exc
+else:  # pragma: no cover
+    exec("def reraise(exc): raise exc[0], exc[1], exc[2]")
diff --git a/hyde/exceptions.py b/hyde/exceptions.py
index 5a93a12..bfb52d5 100644
--- a/hyde/exceptions.py
+++ b/hyde/exceptions.py
@@ -1,10 +1,12 @@
+from hyde._compat import reraise
+
+
 class HydeException(Exception):
 
     """
     Base class for exceptions from hyde
     """
-
     @staticmethod
     def reraise(message, exc_info):
         _, _, tb = exc_info
-        raise HydeException(message).with_traceback(tb)
+        reraise((HydeException(message), None, tb))

```

**Comment by jonafato** [comment]
@lakshmivyas Good catch on the `reraise`. I actually had a change like this one on my original Python 3 support branch that didn't make it into this version. I've updated my commit to include that. Additionally, I've fixed the `pep8` errors introduced by the recent release.

**Comment by lakshmivyas** [comment]
@jonafato - very nice.  I think this PR is ready for merge and a new release.  I've asked a couple of people to test it out with their sites.  Once I hear back from them, I will merge this one.  I also need to add you and @llonchj  to hyde pypi package.

**Comment by jonafato** [comment]
@lakshmivyas :+1: definitely good to have people testing. If they mention any issues they find in this PR before it's merged, I'm happy to fix them.

**Comment by nnarhinen** [comment]
I was asked by @lakshmivyas to test this branch out. I'm lacking in python skills so I'm not sure if this is something in our own code or something else, so I'm just pasting the console output here (`hyde -v gen -r`):

```
09:07:26 hyde Traceback (most recent call last):                                                                                                                                                                                                                                           [7/1395]
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/markdown/__init__.py", line 231, in build_extension
    module = importlib.import_module(ext_name)
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/nnarhinen/.virtualenv/fp5py3/src/hydedown/hydedown/sections.py", line 161, in <module>
    from itertools import izip_longest, tee
ImportError: cannot import name 'izip_longest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/markdown/__init__.py", line 246, in build_extension
    module = importlib.import_module(module_name)
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'markdown.extensions.hydedown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/hyde/generator.py", line 338, in __generate_resource__
    context)
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/hyde/ext/templates/jinja.py", line 889, in render_resource
    out = template.render(context)
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/nnarhinen/flowplayer/www/content/404.html", line 1, in top-level template code
    ---
  File "/Users/nnarhinen/flowplayer/www/layout/site.j2", line 9, in top-level template code
    {% set EMBED = site.config.embed_url -%}
  File "/Users/nnarhinen/flowplayer/www/layout/root.j2", line 71, in top-level template code
    {% block body -%}
  File "/Users/nnarhinen/flowplayer/www/layout/site.j2", line 142, in block "body"
    {{ super() }}
  File "/Users/nnarhinen/flowplayer/www/layout/root.j2", line 75, in block "body"
    {% block wrap -%}
  File "/Users/nnarhinen/flowplayer/www/layout/root.j2", line 88, in block "wrap"
    {% block main -%}
  File "/Users/nnarhinen/flowplayer/www/layout/root.j2", line 98, in block "main"
    {% block content -%}
  File "/Users/nnarhinen/flowplayer/www/layout/root.j2", line 100, in block "content"
    {% markdown -%}{% block markdown -%}{%- endblock %}{%- endmarkdown %}
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/hyde/ext/templates/jinja.py", line 316, in _render_markdown
    return markdown(self.environment, output)
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/hyde/ext/templates/jinja.py", line 163, in markdown
    marked = md.Markdown(**d)
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/markdown/__init__.py", line 185, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/markdown/__init__.py", line 264, in build_extension
    module = importlib.import_module(module_name_old_style)
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'mdx_hydedown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/commando/application.py", line 309, in run
    args.run(self, args)
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/hyde/engine.py", line 102, in gen
    gen.generate_all(incremental=incremental)
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/hyde/generator.py", line 216, in generate_all
    self.__generate_node__(self.site.content, incremental)
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/hyde/generator.py", line 313, in __generate_node__
    self.__generate_resource__(resource, incremental)
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/hyde/generator.py", line 343, in __generate_resource__
    sys.exc_info())
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/hyde/exceptions.py", line 10, in reraise
    reraise(HydeException(message), None, tb)
  File "/Users/nnarhinen/.virtualenv/fp5py3/lib/python3.5/site-packages/hyde/_compat.py", line 41, in reraise
    raise value
TypeError: exceptions must derive from BaseException

 09:07:26 hyde exceptions must derive from BaseException
```

**Comment by nnarhinen** [comment]
With python 2.7 I couldn't find anything obvious that would be broken with this branch.

**Comment by lakshmivyas** [comment]
Thanks so much @nnarhinen.  Looks like other than the issue with exceptions, this is good for python 2.7.x. \cc @jonafato

**Comment by jonafato** [comment]
@lakshmivyas Exception logic updated. It looks like this test was using hydedown, which does not currently have Python 3 support. I can tackle that next but prefer to focus my efforts on Hyde core before moving on to extensions.

**Comment by lakshmivyas** [comment]
@jonafato - +1.  Yeah, moving hydedown to 3.x can wait.

**Comment by lakshmivyas** [comment]
Fantastic work, @jonafato.  :100:

**Pull request merged**
